@echo off
echo Iniciando aplicación web con FastAPI...
echo Versión de Python: %python --version%
echo.
echo Creando entorno virtual...
python -m venv venv

echo Instalando dependencias...
venv\\Scripts\\pip install -r requirements.txt

echo Iniciando servidor...
venv\\Scripts\\python simple_main.py